### ISSUE TITLE
Micro MinimOsd has no reset button 

### ISSUE THREAD

**Issue by CopterFail** [UncleRus/min_raw_osd#17]
The python scripts for data download ask to press a reset button to start the download. The micro minimosd has no reset button. Is it possible to use DTR, as arduino does?

**Comment by UncleRus** [comment]
I added a reset by DTR to the font_uploader.py, but can't check how it's works because no DTR line in my USB-UART bridge.

**Comment by CopterFail** [comment]
uploading fonts works now.

**Comment by CopterFail** [comment]
Can this also be done for the firmware download?

**Comment by UncleRus** [comment]
Hmm... flasher already does reset by DTR.
See line 233 in flasher.py

**Comment by UncleRus** [comment]
I tested flasher.py with optiboot bootloader and it's works. Perhaps the arduino BL is differs from optiboot...

**Comment by CopterFail** [comment]
I'll test another normal size minimosd with reset button. 
The mico mini mosd can be flashed with osd extra setup (windows) and arduino ide.

**Comment by AlessioMorale** [comment]
I had success flashing the firmware to a small minimosd from myrcmart but I had to change flasher.py reducing the baud rate to 57600 to make it work.

**Comment by UncleRus** [comment]
I added "--baudrate" option to flasher.py

**Comment by CopterFail** [comment]
Works perfect now. Thank you.

**Comment by UncleRus** [comment]
Thank you and Alessio!

I'm closing issue.
