### ISSUE TITLE
Micro MinimosdBat2 Voltage

### ISSUE THREAD

**Issue by darul86** [UncleRus/min_raw_osd#18]
Would it be possible to implement showing the bat2 voltage on micro minimosd? i would like to use it to monitor my video lipo. thanks

**Comment by UncleRus** [comment]
I think second bat voltage is a good idea.
Will be added in next version (0.14), which I plan to relese in about two weeks.

**Comment by UncleRus** [comment]
Done. You can test it in release 0.14. Please see wiki to get information about flashing, font uploading and configuring.

**Comment by darul86** [comment]
did a short test late night. seems to work. have to setup the configuration tomorrow again and test it more. thx mate

**Comment by darul86** [comment]
i think theres a problem with the bat symbol of each. my flight bat is 4s showing 14.15v ( thats 3,5375v per cell ) and symbol is full bat.
the second bat is 3s showing 11.93 ( 3.97 per cell ) and symbol is showing 3 quarters.

voltage levels are firmware defaults.

any ideas?

![img_20160604_212550](https://cloud.githubusercontent.com/assets/4730236/15801782/42789d5e-2aa0-11e6-86a2-88e3a9b5038f.jpg)

**Comment by UncleRus** [comment]
Would you please test this hotfix? You need to build firmware by yourself, but if this is a problem, I can build it for you.

**Comment by darul86** [comment]
good job! problem solved. thanks for your fast response and your work.

**Comment by UncleRus** [comment]
You're welcome!
